In [1]:
import numpy as np
import pandas as pd

In [8]:
filename = 'C:/program2/tensorflow/data/day_data_nov.csv'

In [9]:
data = pd.read_csv(filename)
data

      Unnamed: 0    0
0              0  2.0
1              1  2.0
2              2  2.0
3              3  2.0
4              4  2.0
5              5  2.0
6              6  2.0
7              7  2.0
8              8  2.0
9              9  2.0
10            10  2.0
11            11  2.0
12            12  2.0
13            13  2.0
14            14  2.0
15            15  2.0
16            16  2.0
17            17  2.0
18            18  2.0
19            19  2.0
20            20  2.0
21            21  2.0
22            22  2.0
23            23  2.0
24            24  2.0
25            25  2.0
26            26  2.0
27            27  2.0
28            28  2.0
29            29  2.0
...          ...  ...
4290        4290  1.0
4291        4291  1.0
4292        4292  1.0
4293        4293  1.0
4294        4294  1.0
4295        4295  1.0
4296        4296  1.0
4297        4297  1.0
4298        4298  1.0
4299        4299  1.0
4300        4300  1.0
4301        4301  1.0
4302        4302  1.0
4303        4303  1.0
4304        4304  1.0
4305        4305  1.0
4306        4306  1.0
4307        4307  1.0
4308        4308  1.0
4309        4309  1.0
4310        4310  1.0
4311        4311  1.0
4312        4312  1.0
4313        4313  1.0
4314        4314  1.0
4315        4315  1.0
4316        4316  1.0
4317        4317  1.0
4318        4318  1.0
4319        4319  1.0

[4320 rows x 2 columns]