In [18]:
import pandas as pd

In [2]:
name = ['线路','时间','电力消耗情况']
f = pd.read_csv('SET-dec-2013.csv',names = name,header = None)
f

               线路                时间      电力消耗情况
0       DG1000420  2013-12-01 00:00   36.719997
1       DG1000420  2013-12-01 00:10   36.180000
2       DG1000420  2013-12-01 00:20   35.639999
3       DG1000420  2013-12-01 00:30   34.559998
4       DG1000420  2013-12-01 00:40   34.559998
5       DG1000420  2013-12-01 00:50   34.019997
6       DG1000420  2013-12-01 01:00   32.399998
7       DG1000420  2013-12-01 01:10   32.399998
8       DG1000420  2013-12-01 01:20   31.859999
9       DG1000420  2013-12-01 01:30   30.239998
10      DG1000420  2013-12-01 01:40   30.239998
11      DG1000420  2013-12-01 01:50   30.239998
12      DG1000420  2013-12-01 02:00   31.319998
13      DG1000420  2013-12-01 02:10   31.319998
14      DG1000420  2013-12-01 02:20   30.239998
15      DG1000420  2013-12-01 02:30   30.239998
16      DG1000420  2013-12-01 02:40   30.239998
17      DG1000420  2013-12-01 02:50   30.239998
18      DG1000420  2013-12-01 03:00   30.239998
19      DG1000420  2013-12-01 03:10   30.239998
20      DG1000420  2013-12-01 03:20   30.239998
21      DG1000420  2013-12-01 03:30   30.239998
22      DG1000420  2013-12-01 03:40   30.239998
23      DG1000420  2013-12-01 03:50   30.239998
24      DG1000420  2013-12-01 04:00   30.239998
25      DG1000420  2013-12-01 04:10   30.239998
26      DG1000420  2013-12-01 04:20   30.239998
27      DG1000420  2013-12-01 04:30   30.239998
28      DG1000420  2013-12-01 04:40   30.239998
29      DG1000420  2013-12-01 04:50   30.239998
...           ...               ...         ...
821346  DG1056626  2013-12-31 19:00  125.000000
821347  DG1056626  2013-12-31 19:10    0.000000
821348  DG1056626  2013-12-31 19:20    0.000000
821349  DG1056626  2013-12-31 19:30    0.000000
821350  DG1056626  2013-12-31 19:40  119.150002
821351  DG1056626  2013-12-31 19:50  117.175003
821352  DG1056626  2013-12-31 20:00    0.000000
821353  DG1056626  2013-12-31 20:10    0.000000
821354  DG1056626  2013-12-31 20:20  108.875000
821355  DG1056626  2013-12-31 20:30  108.775002
821356  DG1056626  2013-12-31 20:40  105.750000
821357  DG1056626  2013-12-31 20:50  104.474998
821358  DG1056626  2013-12-31 21:00   99.949997
821359  DG1056626  2013-12-31 21:10   97.574997
821360  DG1056626  2013-12-31 21:20   96.175003
821361  DG1056626  2013-12-31 21:30   94.125000
821362  DG1056626  2013-12-31 21:40   92.650002
821363  DG1056626  2013-12-31 21:50   89.875000
821364  DG1056626  2013-12-31 22:00   89.099998
821365  DG1056626  2013-12-31 22:10   88.650002
821366  DG1056626  2013-12-31 22:20   87.349998
821367  DG1056626  2013-12-31 22:30   85.224998
821368  DG1056626  2013-12-31 22:40   83.699997
821369  DG1056626  2013-12-31 22:50   82.625000
821370  DG1056626  2013-12-31 23:00   80.724998
821371  DG1056626  2013-12-31 23:10   79.574997
821372  DG1056626  2013-12-31 23:20   78.625000
821373  DG1056626  2013-12-31 23:30   77.025002
821374  DG1056626  2013-12-31 23:40   76.125000
821375  DG1056626  2013-12-31 23:50   75.775002

[821376 rows x 3 columns]

In [19]:
f1 = pd.read_csv('line.csv')
f1

      SQUAREID    LINESET  NR_UBICAZIONI
0          155  DG1031221              4
1          272  DG1031221             72
2          273  DG1031221             21
3          276  DG1003117             34
4          277  DG1003117              3
5          389  DG1031221             65
6          390  DG1031221              8
7          393  DG1003117             25
8          506  DG1031221             12
9          507  DG1031221             27
10         624  DG1031221              5
11         625  DG1031221              6
12         626  DG1003117              2
13         635  DG1003117              7
14         737  DG1031220              9
15         738  DG1031220              1
16         740  DG1031221              7
17         741  DG1031221            355
18         742  DG1031221             32
19         743  DG1003117             10
20         743  DG1031221             74
21         752  DG1003117              5
22         854  DG1031220             20
23         857  DG1031221              8
24         858  DG1031221             80
25         859  DG1031221            414
26         860  DG1003117              2
27         860  DG1031221            174
28         861  DG1003117             22
29         861  DG1031221              3
...        ...        ...            ...
2545     10628  DG1013503              9
2546     10629  DG1013503             50
2547     10629  DG1013596              1
2548     10631  DG1013504              1
2549     10631  DG1013505             11
2550     10632  DG1013505            173
2551     10638  DG1013505              5
2552     10705  DG1099111              5
2553     10745  DG1013503             12
2554     10746  DG1013503            345
2555     10747  DG1013505             84
2556     10748  DG1013504             21
2557     10748  DG1013505            400
2558     10749  DG1013504              5
2559     10749  DG1013505             13
2560     10750  DG1013504              9
2561     10751  DG1013504              5
2562     10752  DG1013504              1
2563     10866  DG1013504              8
2564     10867  DG1013504              7
2565     10868  DG1013504              9
2566     10980  DG1013503             11
2567     10981  DG1013503              5
2568     10982  DG1013503              1
2569     10982  DG1013504              1
2570     10983  DG1013504              5
2571     10984  DG1013504              2
2572     11097  DG1013503              1
2573     11098  DG1013503              6
2574     11099  DG1013503              3

[2575 rows x 3 columns]

In [47]:
f1.loc[f1['SQUAREID'] == 1206]

    SQUAREID    LINESET  NR_UBICAZIONI
58      1206  DG1031220              3

In [4]:
f2 = pd.read_csv('SET-nov-2013.csv',header = None)
f2

                0                 1          2
0       DG1000420  2013-11-01 00:00  37.439999
1       DG1000420  2013-11-01 00:10  37.439999
2       DG1000420  2013-11-01 00:20  36.000000
3       DG1000420  2013-11-01 00:30  35.279999
4       DG1000420  2013-11-01 00:40  35.279999
5       DG1000420  2013-11-01 00:50  34.199997
6       DG1000420  2013-11-01 01:00  35.279999
7       DG1000420  2013-11-01 01:10  34.199997
8       DG1000420  2013-11-01 01:20  33.119999
9       DG1000420  2013-11-01 01:30  34.739998
10      DG1000420  2013-11-01 01:40  32.939999
11      DG1000420  2013-11-01 01:50  32.399998
12      DG1000420  2013-11-01 02:00  32.399998
13      DG1000420  2013-11-01 02:10  32.399998
14      DG1000420  2013-11-01 02:20  31.859999
15      DG1000420  2013-11-01 02:30  32.399998
16      DG1000420  2013-11-01 02:40  31.319998
17      DG1000420  2013-11-01 02:50  30.959999
18      DG1000420  2013-11-01 03:00  32.219997
19      DG1000420  2013-11-01 03:10  32.399998
20      DG1000420  2013-11-01 03:20  32.399998
21      DG1000420  2013-11-01 03:30  32.399998
22      DG1000420  2013-11-01 03:40  31.319998
23      DG1000420  2013-11-01 03:50  31.139999
24      DG1000420  2013-11-01 04:00  30.779999
25      DG1000420  2013-11-01 04:10  32.399998
26      DG1000420  2013-11-01 04:20  31.319998
27      DG1000420  2013-11-01 04:30  31.319998
28      DG1000420  2013-11-01 04:40  31.319998
29      DG1000420  2013-11-01 04:50  30.959999
...           ...               ...        ...
794488  DG1056626  2013-11-30 19:00  70.949997
794489  DG1056626  2013-11-30 19:10  70.574997
794490  DG1056626  2013-11-30 19:20  70.099998
794491  DG1056626  2013-11-30 19:30  69.900002
794492  DG1056626  2013-11-30 19:40  67.324997
794493  DG1056626  2013-11-30 19:50  66.125000
794494  DG1056626  2013-11-30 20:00  65.500000
794495  DG1056626  2013-11-30 20:10  64.425003
794496  DG1056626  2013-11-30 20:20  63.950001
794497  DG1056626  2013-11-30 20:30  61.724998
794498  DG1056626  2013-11-30 20:40  61.325001
794499  DG1056626  2013-11-30 20:50  62.500000
794500  DG1056626  2013-11-30 21:00  61.950001
794501  DG1056626  2013-11-30 21:10  60.474998
794502  DG1056626  2013-11-30 21:20  59.575001
794503  DG1056626  2013-11-30 21:30  59.775002
794504  DG1056626  2013-11-30 21:40  58.549999
794505  DG1056626  2013-11-30 21:50  56.875000
794506  DG1056626  2013-11-30 22:00  55.599998
794507  DG1056626  2013-11-30 22:10  54.299999
794508  DG1056626  2013-11-30 22:20  53.650002
794509  DG1056626  2013-11-30 22:30  52.625000
794510  DG1056626  2013-11-30 22:40  50.575001
794511  DG1056626  2013-11-30 22:50  49.299999
794512  DG1056626  2013-11-30 23:00  47.275002
794513  DG1056626  2013-11-30 23:10  46.549999
794514  DG1056626  2013-11-30 23:20  44.650002
794515  DG1056626  2013-11-30 23:30  44.599998
794516  DG1056626  2013-11-30 23:40  43.700001
794517  DG1056626  2013-11-30 23:50  43.125000

[794518 rows x 3 columns]